version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - ssbhat
  assignees:
  - ssbhat
  ignore:
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: yara-python
    versions:
    - 4.0.4
    - 4.0.5
  - dependency-name: pyinstaller
    versions:
    - "4.2"
